FROM alpine:3

# Membuat folder hello
RUN mkdir hello

# Memasukkan tulisan ke dalam folder hello di dalam file world.txt
RUN echo "Hello World" > "hello/world.txt"

# Membaca file world.txt di dalam folder hello
RUN cat "hello/world.txt"